services:
  goliath:
    build:
      args:
        - BUILD_TIMESTAMP="${BUILD_TIMESTAMP}"
        - BUILD_HASH="${BUILD_HASH}"
    container_name: "goliath"
    networks:
      - db-network
    ports:
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "./config.ini:/config.ini"
    depends_on:
      crdb-service:
        condition: service_started

  crdb-service:
    image: cockroachdb/cockroach:v19.2.2
    hostname: crdb
    container_name: "crdb-service"
    ports:
      - "8080:8080"
    expose:
      - "26257"
    command: "start-single-node --insecure --advertise-addr=crdb"
    networks:
      - db-network
    volumes:
      - "crdb_volume:/cockroach/cockroach-data"

networks:
  db-network: { }

volumes:
  crdb_volume:
    external: true