services:
  ##############################################################################
  # Prod Environment
  ##############################################################################

  goliath:
    build:
      args:
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP}
        - BUILD_HASH=${BUILD_HASH}
    container_name: "goliath"
    profiles: [ "prod" ]
    depends_on:
      crdb:
        condition: service_started
    networks:
      - crdb-network
    ports:
      - "127.0.0.1:9999:9999"
      - "127.0.0.1:9998:9998"
      - "127.0.0.1:9997:9997"
    volumes:
      - "./config.ini:/config.ini"
      - "/tmp:/tmp"

  ##############################################################################
  # Dev Environment
  ##############################################################################

  frontend-dev: &frontend_dev_template
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    container_name: "frontend_dev"
    stdin_open: true
    profiles: [ "dev" ]
    ports:
      - "3000:3000"
    links:
      - "backend-dev:goliath-dev"
    networks:
      - goliath-network
    volumes:
      - ./frontend:/frontend

  backend-dev: &backend_dev_template
    build:
      dockerfile: dev.Dockerfile
    container_name: "backend_dev"
    profiles: [ "dev" ]
    depends_on:
      crdb:
        condition: service_started
    networks:
      - crdb-network
      - goliath-network
    ports:
      - "9999:9999"
      - "9998:9998"
      - "9997:9997"
    volumes:
      - "./config.ini:/config.ini"
      - "/tmp:/tmp"

  ##############################################################################
  # Debug Environment
  ##############################################################################

  frontend-debug:
    <<: *frontend_dev_template
    container_name: "frontend-debug"
    profiles: [ "debug" ]
    links:
      - "backend-debug:goliath-dev"

  backend-debug:
    <<: *backend_dev_template
    build:
      dockerfile: debug.Dockerfile
    container_name: "backend-debug"
    profiles: [ "debug" ]
    cap_add:
      - SYS_PTRACE
    ports:
      - "9999:9999"
      - "9998:9998"
      - "9997:9997"
      - "40000:40000"
    security_opt:
      - seccomp:unconfined

  ##############################################################################
  # External Services
  ##############################################################################

  crdb:
    image: cockroachdb/cockroach:v23.2.2
    hostname: crdb
    command: "start-single-node --insecure --advertise-addr=crdb --log-dir=/tmp"
    container_name: "crdb-service"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 120s
    expose:
      - "26257"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://crdb:8080/health?ready=1" ]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - crdb-network
      - goliath-network
    ports:
      - "8080:8080"
    volumes:
      - "crdb_volume:/cockroach/cockroach-data"
      - "./backend/schema:/cockroach/scripts"
      - "/tmp:/tmp"

networks:
  crdb-network: { }
  # Only needed in non-prod environments where the frontend is not bundled
  # into the backend.
  goliath-network: { }

volumes:
  crdb_volume:
    external: true