##############################################################################
# External Service Templates
##############################################################################

x-prometheus-base: &prometheus_template
  image: prom/prometheus:v2.51.0
  command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--storage.tsdb.retention.time=15d"
  volumes:
    - ./monitoring/prometheus:/etc/prometheus
    - prometheus_data:/prometheus
  networks:
    goliath-backend:
      aliases:
        - prometheus-server

x-grafana-base: &grafana_template
  image: grafana/grafana:10.4.1
  volumes:
    - grafana_data:/var/lib/grafana
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
  networks:
    - goliath-backend

x-crdb-base: &crdb_template
  image: cockroachdb/cockroach:v23.2.2
  hostname: crdb
  command: "start-single-node --insecure --advertise-addr=crdb --log-dir=/tmp"
  dns: 8.8.8.8
  volumes:
    - "crdb_volume:/cockroach/cockroach-data"
    - "./backend/schema:/cockroach/scripts"
    - "/tmp:/tmp"

services:
  ##############################################################################
  # Prod Environment
  ##############################################################################

  goliath:
    build:
      target: prod
      args:
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP}
        - BUILD_HASH=${BUILD_HASH}
    container_name: "goliath"
    dns: 8.8.8.8
    profiles: ["prod"]
    depends_on:
      crdb:
        condition: service_started
    networks:
      - goliath-backend
    ports:
      - "127.0.0.1:9999:9999"
      - "127.0.0.1:9998:9998"
      - "127.0.0.1:9997:9997"
    volumes:
      - "./config.ini:/config.ini"
      - "/tmp:/tmp"

  crdb:
    <<: *crdb_template
    container_name: "crdb-service"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 120s
    profiles: ["prod"]
    expose:
      - "26257"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://crdb:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - goliath-backend
    ports:
      - "8080:8080"

  prometheus:
    <<: *prometheus_template
    container_name: "prometheus"
    profiles: ["prod"]

  grafana:
    <<: *grafana_template
    container_name: "grafana"
    profiles: ["prod"]
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GRAFANA_SERVER_ROOT_URL}
      - GF_SERVER_DOMAIN=${GRAFANA_SERVER_DOMAIN}

  ##############################################################################
  # Dev Environment
  ##############################################################################

  frontend-dev: &frontend_template
    build:
      target: frontend-dev
    container_name: "frontend_dev"
    stdin_open: true
    profiles: ["dev"]
    ports:
      - "3000:3000"
    links:
      - "backend-dev:goliath-dev"
    networks:
      - goliath-backend-nonprod
    volumes:
      - ./frontend:/frontend

  backend-dev: &backend_template
    build:
      target: dev
    container_name: "backend_dev"
    profiles: ["dev"]
    depends_on:
      crdb-dev:
        condition: service_started
    networks:
      goliath-backend:
        aliases:
          - goliath
      goliath-backend-nonprod:
    ports:
      - "9999:9999"
      - "9998:9998"
      - "9997:9997"
    volumes:
      - "./config.ini:/config.ini"
      - "/tmp:/tmp"

  crdb-dev:
    <<: *crdb_template
    container_name: "crdb-dev"
    profiles: ["dev"]
    ports:
      # Also map 26257 to the host in the non-prod
      - "26257:26257"
    networks:
      - goliath-backend
      - goliath-backend-nonprod

  prometheus-dev:
    <<: *prometheus_template
    container_name: "prometheus-dev"
    profiles: ["dev"]
    ports:
      - "9996:9090"

  grafana-dev:
    <<: *grafana_template
    container_name: "grafana-dev"
    profiles: ["dev"]
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3001
      - GF_SERVER_DOMAIN=localhost

  ##############################################################################
  # Debug Environment
  ##############################################################################

  frontend-debug:
    <<: *frontend_template
    container_name: "frontend-debug"
    profiles: ["debug"]
    links:
      - "backend-debug:goliath-dev"

  backend-debug:
    <<: *backend_template
    build:
      target: debug
    container_name: "backend-debug"
    profiles: ["debug"]
    depends_on:
      crdb-debug:
        condition: service_started
    cap_add:
      - SYS_PTRACE
    ports:
      - "9999:9999"
      - "9998:9998"
      - "9997:9997"
      - "40000:40000"
    security_opt:
      - seccomp:unconfined

  crdb-debug:
    <<: *crdb_template
    container_name: "crdb-debug"
    profiles: ["debug"]
    ports:
      # Also map 26257 to the host in the non-prod
      - "26257:26257"
    networks:
      - goliath-backend
      - goliath-backend-nonprod

  prometheus-debug:
    <<: *prometheus_template
    container_name: "prometheus-debug"
    profiles: ["debug"]
    ports:
      - "9996:9090"

  grafana-debug:
    <<: *grafana_template
    container_name: "grafana-debug"
    profiles: ["debug"]
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3001
      - GF_SERVER_DOMAIN=localhost

##############################################################################
# Networks
##############################################################################

networks:
  goliath-backend: {}
  # Only needed in non-prod environments where the frontend is not bundled
  # into the backend.
  goliath-backend-nonprod: {}

##############################################################################
# Volumes
##############################################################################

volumes:
  crdb_volume:
    external: true
  prometheus_data: {}
  grafana_data: {}
