name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Install protobuf-compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Go protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Compile protobufs
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          protoc --proto_path=. --go_out=backend/admin/ --go-grpc_out=backend/admin/ \
            --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative \
            backend/admin/admin.proto

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile
        working-directory: frontend

      - name: Run backend tests
        run: go test ./backend/...

      - name: Run frontend tests
        run: bun test
        working-directory: frontend
